version: "3.9"

services:
  db:
    container_name: demo-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgressql

volumes:
  db:
